"""initial schema

Revision ID: 8989f7e6d5e8
Revises: 
Create Date: 2026-03-27 14:04:16.376058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8989f7e6d5e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.Text(), nullable=False),
    sa.Column('entidad', sa.Text(), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('detalle_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entidad_id'), 'audit_logs', ['entidad_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('ciudad', sa.String(length=120), nullable=False),
    sa.Column('provincia', sa.String(length=120), nullable=False),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'RRHH', 'LIDER_SOLICITANTE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_table('job_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_puesto', sa.String(length=255), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('seniority', sa.String(length=100), nullable=False),
    sa.Column('modalidad', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('descripcion_general', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'ACTIVO', 'ARCHIVADO', name='jobprofilestatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_profiles_area_id'), 'job_profiles', ['area_id'], unique=False)
    op.create_index(op.f('ix_job_profiles_created_by'), 'job_profiles', ['created_by'], unique=False)
    op.create_index(op.f('ix_job_profiles_nombre_puesto'), 'job_profiles', ['nombre_puesto'], unique=False)
    op.create_table('job_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_profile_id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('tipo_respuesta', sa.Enum('TEXTO', 'BOOLEANO', 'NUMERICO', 'OPCION', name='questiontype'), nullable=False),
    sa.Column('obligatoria', sa.Boolean(), nullable=False),
    sa.Column('eliminatoria', sa.Boolean(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_profile_id'], ['job_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_questions_job_profile_id'), 'job_questions', ['job_profile_id'], unique=False)
    op.create_table('job_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_profile_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('obligatorio', sa.Boolean(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('valor_esperado', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['job_profile_id'], ['job_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requirements_job_profile_id'), 'job_requirements', ['job_profile_id'], unique=False)
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_profile_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('titulo_publicacion', sa.String(length=255), nullable=False),
    sa.Column('descripcion_publicacion', sa.Text(), nullable=False),
    sa.Column('fecha_apertura', sa.Date(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTA', 'PAUSADA', 'CERRADA', name='vacancystatus'), nullable=False),
    sa.Column('qr_token', sa.String(length=120), nullable=False),
    sa.Column('public_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_profile_id'], ['job_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_area_id'), 'vacancies', ['area_id'], unique=False)
    op.create_index(op.f('ix_vacancies_branch_id'), 'vacancies', ['branch_id'], unique=False)
    op.create_index(op.f('ix_vacancies_company_id'), 'vacancies', ['company_id'], unique=False)
    op.create_index(op.f('ix_vacancies_job_profile_id'), 'vacancies', ['job_profile_id'], unique=False)
    op.create_index(op.f('ix_vacancies_qr_token'), 'vacancies', ['qr_token'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('fecha_postulacion', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('POSTULADO', 'EN_ANALISIS', 'RECOMENDADO', 'REVISION_RRHH', 'PRESELECCIONADO', 'ENTREVISTA_PENDIENTE', 'ENTREVISTADO', 'EVALUACION_FINAL', 'RECHAZADO', 'CONTRATADO', 'RESERVA', name='applicationstatus'), nullable=False),
    sa.Column('consentimiento_datos', sa.Boolean(), nullable=False),
    sa.Column('cv_file_path', sa.String(length=500), nullable=False),
    sa.Column('cv_text_extracted', sa.Text(), nullable=False),
    sa.Column('fuente', sa.String(length=120), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_vacancy_id'), 'applications', ['vacancy_id'], unique=False)
    op.create_table('application_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('job_question_id', sa.Integer(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['job_question_id'], ['job_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_answers_application_id'), 'application_answers', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_answers_job_question_id'), 'application_answers', ['job_question_id'], unique=False)
    op.create_table('application_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('score_formacion', sa.Integer(), nullable=False),
    sa.Column('score_experiencia', sa.Integer(), nullable=False),
    sa.Column('score_tecnico', sa.Integer(), nullable=False),
    sa.Column('score_preguntas', sa.Integer(), nullable=False),
    sa.Column('score_competencias', sa.Integer(), nullable=False),
    sa.Column('clasificacion', sa.Text(), nullable=False),
    sa.Column('resumen_analisis', sa.Text(), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_scores_application_id'), 'application_scores', ['application_id'], unique=True)
    op.create_table('candidate_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_notes_application_id'), 'candidate_notes', ['application_id'], unique=False)
    op.create_index(op.f('ix_candidate_notes_user_id'), 'candidate_notes', ['user_id'], unique=False)
    op.create_table('score_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_score_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('FORTALEZA', 'OBSERVACION', 'DESCARTE', 'ALERTA', name='scorereasontype'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('impacto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_score_id'], ['application_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_reasons_application_score_id'), 'score_reasons', ['application_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_reasons_application_score_id'), table_name='score_reasons')
    op.drop_table('score_reasons')
    op.drop_index(op.f('ix_candidate_notes_user_id'), table_name='candidate_notes')
    op.drop_index(op.f('ix_candidate_notes_application_id'), table_name='candidate_notes')
    op.drop_table('candidate_notes')
    op.drop_index(op.f('ix_application_scores_application_id'), table_name='application_scores')
    op.drop_table('application_scores')
    op.drop_index(op.f('ix_application_answers_job_question_id'), table_name='application_answers')
    op.drop_index(op.f('ix_application_answers_application_id'), table_name='application_answers')
    op.drop_table('application_answers')
    op.drop_index(op.f('ix_applications_vacancy_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_vacancies_qr_token'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_job_profile_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_company_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_branch_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_area_id'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_job_requirements_job_profile_id'), table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_index(op.f('ix_job_questions_job_profile_id'), table_name='job_questions')
    op.drop_table('job_questions')
    op.drop_index(op.f('ix_job_profiles_nombre_puesto'), table_name='job_profiles')
    op.drop_index(op.f('ix_job_profiles_created_by'), table_name='job_profiles')
    op.drop_index(op.f('ix_job_profiles_area_id'), table_name='job_profiles')
    op.drop_table('job_profiles')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('companies')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_audit_logs_entidad_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('areas')
    # ### end Alembic commands ###
